language: php

# optionally set up exclusions and allowed failures in the matrix
matrix:
  include:
  - php: 7.2
    dist: xenial
    env:
      - DB=pgsql
    sudo: required
    services:
      - postgresql
      
# extensiones
before_install:

addons:
    apt:
        packages:
        - php7.2-xml
        - php7.2-mbstring
        - php7.2-mcrypt
        - php7.2-gd
        - php7.2-zip
        - php7.2-pgsql
install:
  - wget https://github.com/isurgob/isurgob/archive/master.zip
  - unzip master.zip
  
# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - cd db
  - psql -h localhost -U postgres -f "a-pgbackup_sam_logico-2019-05.sql";
  - psql -h localhost -U postgres -f "b-pgbackup_sam_dataaux-2019-05.sql";

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
#script: phpunit --configuration phpunit_$DB.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  #  irc: "irc.freenode.org#yourfavouriteroomfortravis"
  email: "sandracmart@gmail.com"